# Harbor OVA drone.
---
workspace:
  base: /drone
  path: src/github.com/vmware/harbor

pipeline:
  clone:
    image: plugins/git
    tags: true
    recursive: false

  integration-test-on-pr:
    image: vmware/harbor-e2e-engine:1.39
    pull: true
    privileged: true
    environment:
      BIN: bin
      GOPATH: /drone
      SHELL: /bin/bash
      LOG_TEMP_DIR: install-logs
      HARBOR_ADMIN: ${HARBOR_ADMIN}
      HARBOR_PASSWORD: ${HARBOR_PASSWORD}
      DHCP: ${DHCP}
      PROTOCOL: ${PROTOCOL}
      USER: ${USER}
      PASSWORD: ${PASSWORD}
      HOST: ${HOST}
      DATASTORE: ${DATASTORE}
      CLUSTER: ${CLUSTER}
      DATACENTER: ${DATACERTER}      
    commands:
      - tests/integration_ova.sh
    when:
      status: success

