apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nginx-apps
    spec:
      containers:
      - name: nginx-app
        image: vmware/nginx-photon:1.11.13
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: config
          mountPath: /etc/nginx
      volumes:
      - name: config
        configMap:
          name: harbor-nginx-config
          items:
          - key: config
            path: nginx.conf
          - key: pkey
            path: https.key
          - key: cert
            path: https.crt
