---
#Protocol used to serve
protocol: "https"

#Config certification if use 'https' protocol
https_config:
  cert: "../server.crt"
  key: "../server.key"

#Server listening port
port: 9443

#Worker pool
worker_pool:
  #Worker concurrency
  workers: 10
  backend: "redis"
  #Additional config if use 'redis' backend
  redis_pool:
    #redis://[arbitrary_username:password@]ipaddress:port/database_index
    #or ipaddress:port[,weight,password,database_index]
    redis_url: "redis:6379"
    namespace: "harbor_job_service"

#Logger for job
logger:
  path: "/tmp/job_logs"
  level: "INFO"
  archive_period: 1 #days

#Admin server endpoint
admin_server: "http://127.0.0.1:8888"

